
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=UTC
      username: root
      password: pure6671.
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
